const INIT_DEPARTMENTS = [
  {
    id: "d1",
    name: "Engineering",
    code: "ENG",
    budget: 2000000,
    description: "Software & infrastructure",
  },
  {
    id: "d2",
    name: "Human Resources",
    code: "HR",
    budget: 500000,
    description: "People ops & culture",
  },
  {
    id: "d3",
    name: "Design",
    code: "DES",
    budget: 600000,
    description: "Product & brand design",
  },
  {
    id: "d4",
    name: "Finance",
    code: "FIN",
    budget: 300000,
    description: "Financial planning",
  },
  {
    id: "d5",
    name: "Marketing",
    code: "MKT",
    budget: 450000,
    description: "Growth & brand",
  },
];

const INIT_EMPLOYEES = [
  {
    id: "e1",
    employeeId: "EMP-0001",
    firstName: "Alex",
    lastName: "Morgan",
    email: "admin@ems.com",
    password: "admin123",
    role: "SUPER_ADMIN",
    gender: "MALE",
    status: "ACTIVE",
    departmentId: "d1",
    designation: "CEO",
    salary: 200000,
    hireDate: "2020-01-15",
    city: "New York",
    phone: "+1-555-1001",
  },
  {
    id: "e2",
    employeeId: "EMP-0002",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "hr@ems.com",
    password: "hr123",
    role: "HR_MANAGER",
    gender: "FEMALE",
    status: "ACTIVE",
    departmentId: "d2",
    designation: "HR Director",
    salary: 95000,
    hireDate: "2020-03-01",
    city: "San Francisco",
    phone: "+1-555-1002",
  },
  {
    id: "e3",
    employeeId: "EMP-0003",
    firstName: "David",
    lastName: "Chen",
    email: "manager@ems.com",
    password: "mgr123",
    role: "MANAGER",
    gender: "MALE",
    status: "ACTIVE",
    departmentId: "d1",
    designation: "Eng Manager",
    salary: 110000,
    hireDate: "2020-06-15",
    city: "Chicago",
    phone: "+1-555-1003",
  },
  {
    id: "e4",
    employeeId: "EMP-0004",
    firstName: "Emily",
    lastName: "Davis",
    email: "emp@ems.com",
    password: "emp123",
    role: "EMPLOYEE",
    gender: "FEMALE",
    status: "ACTIVE",
    departmentId: "d3",
    designation: "Senior Designer",
    salary: 80000,
    hireDate: "2021-02-01",
    city: "Austin",
    phone: "+1-555-1004",
  },
  {
    id: "e5",
    employeeId: "EMP-0005",
    firstName: "James",
    lastName: "Wilson",
    email: "jwilson@ems.com",
    password: "pass123",
    role: "EMPLOYEE",
    gender: "MALE",
    status: "ACTIVE",
    departmentId: "d1",
    designation: "Sr. Developer",
    salary: 95000,
    hireDate: "2021-04-10",
    city: "Seattle",
    phone: "+1-555-1005",
  },
  {
    id: "e6",
    employeeId: "EMP-0006",
    firstName: "Priya",
    lastName: "Patel",
    email: "ppatel@ems.com",
    password: "pass123",
    role: "EMPLOYEE",
    gender: "FEMALE",
    status: "PROBATION",
    departmentId: "d3",
    designation: "UI Designer",
    salary: 72000,
    hireDate: "2023-09-01",
    city: "Boston",
    phone: "+1-555-1006",
  },
  {
    id: "e7",
    employeeId: "EMP-0007",
    firstName: "Marcus",
    lastName: "Lee",
    email: "mlee@ems.com",
    password: "pass123",
    role: "EMPLOYEE",
    gender: "MALE",
    status: "ON_LEAVE",
    departmentId: "d2",
    designation: "HR Specialist",
    salary: 65000,
    hireDate: "2022-01-20",
    city: "Denver",
    phone: "+1-555-1007",
  },
  {
    id: "e8",
    employeeId: "EMP-0008",
    firstName: "Nina",
    lastName: "Kowalski",
    email: "nkowal@ems.com",
    password: "pass123",
    role: "EMPLOYEE",
    gender: "FEMALE",
    status: "ACTIVE",
    departmentId: "d4",
    designation: "Senior Accountant",
    salary: 78000,
    hireDate: "2021-08-15",
    city: "Miami",
    phone: "+1-555-1008",
  },
  {
    id: "e9",
    employeeId: "EMP-0009",
    firstName: "Tom",
    lastName: "Garcia",
    email: "tgarcia@ems.com",
    password: "pass123",
    role: "EMPLOYEE",
    gender: "MALE",
    status: "ACTIVE",
    departmentId: "d5",
    designation: "Marketing Lead",
    salary: 70000,
    hireDate: "2022-05-01",
    city: "Portland",
    phone: "+1-555-1009",
  },
  {
    id: "e10",
    employeeId: "EMP-0010",
    firstName: "Aisha",
    lastName: "Rahman",
    email: "arahman@ems.com",
    password: "pass123",
    role: "EMPLOYEE",
    gender: "FEMALE",
    status: "ACTIVE",
    departmentId: "d1",
    designation: "Junior Developer",
    salary: 55000,
    hireDate: "2023-11-01",
    city: "Nashville",
    phone: "+1-555-1010",
  },
];

const PAYROLLS = INIT_EMPLOYEES.map((e) => {
  const months = [];
  for (let m = 10; m <= 12; m++) {
    const bonus = Math.round((e.salary * 0.05) / 12);
    const tax = Math.round((e.salary * 0.18) / 12);
    months.push({
      id: `p${e.id}${m}`,
      employeeId: e.id,
      month: m,
      year: 2024,
      basicSalary: Math.round(e.salary / 12),
      bonus,
      tax,
      deductions: 200,
      netSalary: Math.round(e.salary / 12) + bonus - tax - 200,
      status: "PAID",
    });
  }
  months.push({
    id: `p${e.id}1`,
    employeeId: e.id,
    month: 1,
    year: 2025,
    basicSalary: Math.round(e.salary / 12),
    bonus: Math.round((e.salary * 0.05) / 12),
    tax: Math.round((e.salary * 0.18) / 12),
    deductions: 200,
    netSalary:
      Math.round(e.salary / 12) +
      Math.round((e.salary * 0.05) / 12) -
      Math.round((e.salary * 0.18) / 12) -
      200,
    status: "PROCESSED",
  });
  return months;
}).flat();

const HEADCOUNT = [
  { month: "Aug", count: 7 },
  { month: "Sep", count: 7 },
  { month: "Oct", count: 8 },
  { month: "Nov", count: 8 },
  { month: "Dec", count: 9 },
  { month: "Jan", count: 10 },
];
