// lib/styles.ts
import type { CSSProperties } from "react";

export const S: Record<string, CSSProperties> = {
  h1: {
    fontSize: 22,
    fontWeight: 700,
    color: "#e8e0d0",
    margin: 0,
  },
  h2: {
    fontSize: 14,
    fontWeight: 600,
    color: "#c8c0b0",
    margin: 0,
  },
  sub: {
    fontSize: 12,
    color: "#6b6660",
    marginTop: 4,
  },
  card: {
    background: "#111111",
    border: "1px solid #1e1e1e",
    borderRadius: 12,
    overflow: "hidden",
  },
  cardSm: {
    background: "#111111",
    border: "1px solid #1e1e1e",
    borderRadius: 10,
    padding: "12px 14px",
  },
  input: {
    background: "#0a0a0a",
    border: "1px solid #252525",
    borderRadius: 8,
    padding: "9px 12px",
    fontSize: 13,
    color: "#c8c0b0",
    width: "100%",
    fontFamily: "inherit",
  },
  textarea: {
    background: "#0a0a0a",
    border: "1px solid #252525",
    borderRadius: 8,
    padding: "9px 12px",
    fontSize: 13,
    color: "#c8c0b0",
    width: "100%",
    fontFamily: "inherit",
    resize: "vertical" as const,
  },
  select: {
    background: "#0a0a0a",
    border: "1px solid #252525",
    borderRadius: 8,
    padding: "9px 12px",
    fontSize: 13,
    color: "#c8c0b0",
    width: "100%",
  },
  label: {
    display: "block",
    fontSize: 11,
    color: "#6b6660",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  btnPrimary: {
    background: "#d4a853",
    border: "none",
    borderRadius: 8,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 600,
    color: "#0a0a0a",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  btnSecondary: {
    background: "transparent",
    border: "1px solid #252525",
    borderRadius: 8,
    padding: "8px 16px",
    fontSize: 13,
    color: "#c8c0b0",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  btnIcon: {
    background: "transparent",
    border: "1px solid #252525",
    borderRadius: 6,
    width: 28,
    height: 28,
    fontSize: 14,
    color: "#6b6660",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  // th: {
  //   textAlign: "left",
  //   padding: "12px 12px",
  //   fontSize: 11,
  //   fontWeight: 500,
  //   color: "#4a4540",
  //   textTransform: "uppercase",
  //   letterSpacing: "0.05em",
  //   borderBottom: "1px solid #1a1a1a",
  // },
  // td: {
  //   padding: "10px 12px",
  //   fontSize: 13,
  //   color: "#8a8070",
  //   borderBottom: "1px solid #1a1a1a",
  // },
  th: {
    padding: "10px 14px",
    fontSize: 11,
    fontWeight: 600,
    color: "#4a4540",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    textAlign: "left", // ✅ now correctly typed
    borderBottom: "1px solid #1a1a1a",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "13px 14px",
    fontSize: 13,
    color: "#c8c0b0",
    borderBottom: "1px solid #171717",
    verticalAlign: "middle",
  },
  sidebar: {
    width: 220,
    background: "#0a0a0a",
    borderRight: "1px solid #1a1a1a",
    height: "100vh",
    position: "fixed" as const,
    left: 0,
    top: 0,
    display: "flex",
    flexDirection: "column" as const,
  },
  overlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(0,0,0,0.8)",
    backdropFilter: "blur(4px)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modal: {
    background: "#111111",
    border: "1px solid #1e1e1e",
    borderRadius: 16,
    width: "100%",
    maxHeight: "90vh",
    display: "flex",
    flexDirection: "column" as const,
  },
};
